
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi