
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fastapi
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apilocal